name: advice_slip_test
description: A new Flutter project for working with Advice Slip Api.


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  bloc_test: ^9.0.3
  flutter_bloc: ^8.0.1
  connectivity_plus: ^2.3.6
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0-dev
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

